name: Test

on: [push, pull_request]

jobs:
  test-linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install --upgrade pip wheel setuptools
      - run: pip install pytest
      - run: pip install .
      - run: pytest -v